### ISSUE TITLE
Chainquery stopped at block 357741

### ISSUE THREAD

**Issue by tiger5226** [lbryio/chainquery#13]
```
INFO[2018-05-02T19:29:24-04:00] Running daemon iteration 0                   
INFO[2018-05-02T19:29:24-04:00] Height357740                                 
ERRO[2018-05-02T19:29:27-04:00] Vout Error->Datastore(PUTCLAIM): : Error 1364: Field 'fee_address' doesn't have a default value
model: unable to insert into claim
github.com/lbryio/chainquery/model.(*Claim).Insert
        /Users/Mark/go/src/github.com/lbryio/chainquery/model/claim.go:1357
github.com/lbryio/chainquery/model.(*Claim).InsertG
        /Users/Mark/go/src/github.com/lbryio/chainquery/model/claim.go:1274
github.com/lbryio/chainquery/datastore.PutClaim
        /Users/Mark/go/src/github.com/lbryio/chainquery/datastore/datastore.go:195
github.com/lbryio/chainquery/daemon/processing.processClaimNameScript
        /Users/Mark/go/src/github.com/lbryio/chainquery/daemon/processing/claims.go:75
github.com/lbryio/chainquery/daemon/processing.processAsClaim
        /Users/Mark/go/src/github.com/lbryio/chainquery/daemon/processing/claims.go:22
github.com/lbryio/chainquery/daemon/processing.processScript
        /Users/Mark/go/src/github.com/lbryio/chainquery/daemon/processing/outpoints.go:256
github.com/lbryio/chainquery/daemon/processing.ProcessVout
        /Users/Mark/go/src/github.com/lbryio/chainquery/daemon/processing/outpoints.go:215
github.com/lbryio/chainquery/daemon/processing.VoutProcessor
        /Users/Mark/go/src/github.com/lbryio/chainquery/daemon/processing/outpoints.go:56
runtime.goexit
        /usr/local/Cellar/go/1.9.4/libexec/src/runtime/asm_amd64.s:2337 
panic: Datastore(PUTCLAIM): : Error 1364: Field 'fee_address' doesn't have a default value
model: unable to insert into claim
github.com/lbryio/chainquery/model.(*Claim).Insert
        /Users/Mark/go/src/github.com/lbryio/chainquery/model/claim.go:1357
github.com/lbryio/chainquery/model.(*Claim).InsertG
        /Users/Mark/go/src/github.com/lbryio/chainquery/model/claim.go:1274
github.com/lbryio/chainquery/datastore.PutClaim
        /Users/Mark/go/src/github.com/lbryio/chainquery/datastore/datastore.go:195
github.com/lbryio/chainquery/daemon/processing.processClaimNameScript
        /Users/Mark/go/src/github.com/lbryio/chainquery/daemon/processing/claims.go:75
github.com/lbryio/chainquery/daemon/processing.processAsClaim
        /Users/Mark/go/src/github.com/lbryio/chainquery/daemon/processing/claims.go:22
github.com/lbryio/chainquery/daemon/processing.processScript
        /Users/Mark/go/src/github.com/lbryio/chainquery/daemon/processing/outpoints.go:256
github.com/lbryio/chainquery/daemon/processing.ProcessVout
        /Users/Mark/go/src/github.com/lbryio/chainquery/daemon/processing/outpoints.go:215
github.com/lbryio/chainquery/daemon/processing.VoutProcessor
        /Users/Mark/go/src/github.com/lbryio/chainquery/daemon/processing/outpoints.go:56
runtime.goexit
        /usr/local/Cellar/go/1.9.4/libexec/src/runtime/asm_amd64.s:2337

goroutine 22 [running]:
github.com/lbryio/chainquery/daemon/processing.ProcessTx(0xc42025a960, 0x5adb8a4a, 0x0, 0x0)
        /Users/Mark/go/src/github.com/lbryio/chainquery/daemon/processing/transactions.go:144 +0xea6
github.com/lbryio/chainquery/daemon.runBlockProcessing(0xc42023c408)
        /Users/Mark/go/src/github.com/lbryio/chainquery/daemon/daemon.go:166 +0x53e
created by github.com/lbryio/chainquery/daemon.daemonIteration
        /Users/Mark/go/src/github.com/lbryio/chainquery/daemon/daemon.go:100 +0x1eb
exit status 2
```

**Comment by tiger5226** [comment]
This was the result of adding a column to chainquery schema as not null but the release running did not contain the column so it did not send the default empty string to mysql causing block processing failure. I made the column nullable and will correct this when the new release is installed.

**Comment by tiger5226** [comment]
This has been solved with the latest release of chainquery.
